In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("suv_data.csv")

In [3]:
x = data.iloc[:,[2,3]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [4]:
y = data.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25)
#feature scaling 
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()  #created object

In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
data.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
x_train

array([[    40,  57000],
       [    37,  93000],
       [    58, 101000],
       [    35,  57000],
       [    52,  38000],
       [    47,  47000],
       [    59,  83000],
       [    59,  88000],
       [    21,  72000],
       [    53,  72000],
       [    35,  79000],
       [    31,  76000],
       [    26,  17000],
       [    35,  50000],
       [    46,  88000],
       [    35,  22000],
       [    47,  50000],
       [    37,  57000],
       [    19,  76000],
       [    20,  23000],
       [    59, 143000],
       [    47, 113000],
       [    31,  68000],
       [    48,  33000],
       [    37,  55000],
       [    54,  26000],
       [    34,  43000],
       [    26,  16000],
       [    57,  33000],
       [    27,  89000],
       [    20,  82000],
       [    40,  61000],
       [    39,  42000],
       [    48, 138000],
       [    19,  19000],
       [    27,  58000],
       [    35,  44000],
       [    36, 126000],
       [    59,  42000],
       [    38,  71000],


In [9]:
x_train = scale.fit_transform(x_train)
x_train

array([[ 2.62470748e-01, -4.00621433e-01],
       [-3.42926605e-02,  6.35220433e-01],
       [ 2.04305120e+00,  8.65407515e-01],
       [-2.32134933e-01, -4.00621433e-01],
       [ 1.44952438e+00, -9.47315751e-01],
       [ 9.54918700e-01, -6.88355284e-01],
       [ 2.14197233e+00,  3.47486582e-01],
       [ 2.14197233e+00,  4.91353507e-01],
       [-1.61703084e+00,  3.09793447e-02],
       [ 1.54844552e+00,  3.09793447e-02],
       [-2.32134933e-01,  2.32393041e-01],
       [-6.27819477e-01,  1.46072885e-01],
       [-1.12242516e+00, -1.55155684e+00],
       [-2.32134933e-01, -6.02035129e-01],
       [ 8.55997564e-01,  4.91353507e-01],
       [-2.32134933e-01, -1.40768991e+00],
       [ 9.54918700e-01, -6.02035129e-01],
       [-3.42926605e-02, -4.00621433e-01],
       [-1.81487311e+00,  1.46072885e-01],
       [-1.71595197e+00, -1.37891653e+00],
       [ 2.14197233e+00,  2.07388969e+00],
       [ 9.54918700e-01,  1.21068814e+00],
       [-6.27819477e-01, -8.41141960e-02],
       [ 1.

In [10]:
x_test = scale.fit_transform(x_test)
x_test

array([[-0.13818053,  0.2468478 ],
       [-0.13818053,  0.15190634],
       [ 1.08620395,  2.52544291],
       [-0.22563657, -0.38609528],
       [-0.75037277, -0.54433105],
       [ 0.91129188, -1.20892129],
       [ 0.03673153,  2.14567706],
       [-0.13818053,  0.43673073],
       [-1.01274088, -1.46209853],
       [-1.36256501, -1.46209853],
       [ 1.08620395,  2.14567706],
       [ 1.87330826,  1.13296812],
       [-0.3130926 ,  0.18355349],
       [-0.3130926 ,  0.18355349],
       [-0.48800467, -0.79750829],
       [-0.83782881,  0.43673073],
       [-0.92528484, -0.22785951],
       [ 1.61094015,  0.2468478 ],
       [-0.0507245 , -0.5126839 ],
       [ 0.29909964, -0.06962374],
       [-0.75037277,  0.43673073],
       [ 0.2116436 , -0.67091967],
       [-0.57546071,  1.06967382],
       [ 0.73637981, -0.48103675],
       [ 0.2116436 ,  0.65826081],
       [ 0.82383584,  0.9430852 ],
       [ 1.87330826, -0.76586113],
       [ 1.52348412,  1.19626243],
       [-0.13818053,

In [11]:
#kNN Classifier

In [12]:
from sklearn.neighbors import KNeighborsClassifier
cr = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski',p=2)
cr.fit(x_train,y_train)
cr.predict(x_test)

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [13]:
y_pred = cr.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.92

In [15]:
#SVM Classifier

In [16]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear',random_state=0)
svc.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [17]:
y_pred = svc.predict(x_test)
accuracy_score(y_test,y_pred)

0.82

In [18]:
#Decision Tree

In [19]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy',random_state=0)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [20]:
y_pred = dtc.predict(x_test)
accuracy_score(y_test,y_pred)

0.81

In [21]:
#Random Forest

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, criterion='entropy')
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [23]:
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.84

In [24]:
#Gaussian Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [26]:
y_pred = gnb.predict(x_test)
accuracy_score(y_test,y_pred)

0.85